last_build_profile = "common=RELEASE,gnat_native=RELEASE,gnatcoll=RELEASE,gnatcoll_iconv=RELEASE,gnatcoll_sql=RELEASE,gnatcoll_sqlite=RELEASE,gnatcoll_xref=RELEASE,language=DEVELOPMENT,libgpr=RELEASE,shared=RELEASE,vss=RELEASE,xmlada=RELEASE"

